### ISSUE TITLE
[Feature Request] Add blacklist item

### ISSUE THREAD

**Issue by SnowCutieOwO** [fhebuterne/MarketPlace#45]
### Feature related to a problem ?

``` YAML
blacklist:
  item-lore:
    - contain: 'Untradable'
  item-id:
    - bedrock
    - barrier
```

This would be useful for servers have custom items. Thanks!
